server:
  port: 80
spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/mega_news_db
    password: 123
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
        type: trace.sql=true
#    hibernate:
#      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: wwxeww1wwxeww@gmail.com
    password: mmzi sfot cdjs mgwc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  flyway:
    enabled: true
    locations: classpath:/db/migration
    schemas: public
    create-schemas: true
#  liquibase:
#    enabled: false
  cache:
    redis:
      time-to-live: 28800000
app:
  jwt:
    expireDays: 7
    secretKey: '03d2430e18744da8db2b8dbd64a64977be5c1a7f06d52197c9b8113a3b552c69'
  base-path: 'C:\Users\User\realProjects\app-mega-news\files'

  admin:
    username: iqminus1
    firstName: Abdulaziz
    lastName: Qodirov
    email: wwxeww1wwxeww@gmail.com
    password: 123

  url:
    verification: http://localhost/api/v1/auth/verification

  code:
    attempt: 5
