create table code
(
    id        integer generated by default as identity not null,
    create_by integer,
    update_by integer,
    deleted   boolean                                  not null,
    create_at timestamp without time zone,
    update_at timestamp without time zone,
    email     varchar(256)                             not null unique,
    code      varchar(6)                               not null,
    attempt   int check ( attempt != 0
)
    );