create table attachment
(
    id            integer generated by default as identity
        primary key,
    create_at     timestamp(6),
    update_at     timestamp(6),
    deleted       boolean not null,
    create_by     integer,
    update_by     integer,
    content_type  varchar(255),
    name          varchar(255),
    original_name varchar(255),
    path          varchar(255),
    size          bigint
);



create table category
(
    id        integer generated by default as identity
        primary key,
    create_at timestamp(6),
    update_at timestamp(6),
    deleted   boolean not null,
    create_by integer,
    update_by integer,
    name      varchar(255)
);



create table code
(
    id        integer generated by default as identity
        primary key,
    create_at timestamp(6),
    update_at timestamp(6),
    deleted   boolean not null,
    attempt   integer,
    code      varchar(255),
    email     varchar(255)
);



create table role
(
    id          integer generated by default as identity
        primary key,
    create_at   timestamp(6),
    update_at   timestamp(6),
    deleted     boolean not null,
    create_by   integer,
    update_by   integer,
    name        varchar(255),
    permissions varchar(255)[],
    type        smallint
        constraint role_type_check
            check ((type >= 0) AND (type <= 3))
);



create table users
(
    id         integer generated by default as identity
        primary key,
    create_at  timestamp(6),
    update_at  timestamp(6),
    deleted    boolean not null,
    create_by  integer,
    update_by  integer,
    email      varchar(255),
    enable     boolean not null,
    first_name varchar(255),
    last_name  varchar(255),
    password   varchar(255),
    username   varchar(255),
    role_id    integer
        constraint fk4qu1gr772nnf6ve5af002rwya
            references role
);



create table employee
(
    id        integer generated by default as identity
        primary key,
    create_at timestamp(6),
    update_at timestamp(6),
    deleted   boolean not null,
    create_by integer,
    update_by integer,
    position  varchar(255),
    user_id   integer
        constraint fkhal2duyxxjtadykhxos7wd3wg
            references users
);



create table team
(
    id                   integer generated by default as identity
        primary key,
    create_at            timestamp(6),
    update_at            timestamp(6),
    deleted              boolean not null,
    create_by            integer,
    update_by            integer,
    email                varchar(255),
    fax                  varchar(255),
    latitude             bigint  not null,
    location_description varchar(255),
    longitude            bigint  not null,
    name                 varchar(255),
    phone_number         varchar(255),
    leader_id            integer
        constraint fkranh7xhm6dlnjgmcbl574hpik
            references employee
);



create table post
(
    id            integer generated by default as identity
        primary key,
    create_at     timestamp(6),
    update_at     timestamp(6),
    deleted       boolean not null,
    create_by     integer,
    update_by     integer,
    explanation   varchar(255),
    tags          varchar(255),
    title         varchar(255),
    background_id integer
        constraint fkr1uplqgsiqyoi1qvc2k2uyqv0
            references attachment,
    team_id       integer
        constraint fkp50yuj3g6cnce6rtt5d6hc3k5
            references team,
    wallpaper_id  integer
        constraint fko2pq8e1371bso50t31lalai8h
            references attachment
);



create table post_attachments
(
    post_id        integer not null
        constraint fk266ujgrq53yo4cox5md5jq3uo
            references post,
    attachments_id integer not null
        constraint fkgn6mjtv6fynmaa724xskfl0s8
            references attachment
);



create table team_teammates
(
    team_id      integer not null
        constraint fkaj1x97kkatmbvmf8t3yodno5q
            references team,
    teammates_id integer not null
        constraint fkok2h04brl2gcejtq1i9wlgshb
            references employee
);



create table user_profile
(
    id        integer generated by default as identity
        primary key,
    create_at timestamp(6),
    update_at timestamp(6),
    deleted   boolean not null,
    create_by integer,
    update_by integer,
    banner_id integer
        constraint fkn8c9gx7t7t25q5d3wdimqdjp0
            references attachment,
    user_id   integer
        constraint fkuganfwvnbll4kn2a3jeyxtyi
            references users
);



create table user_profile_image_profile
(
    user_profile_id  integer not null
        constraint fke6q4u5xd6emceb9gvw27eicp7
            references user_profile,
    image_profile_id integer not null
        constraint fk533tygckar8xvhdydoaun5l7s
            references attachment
);



