create table attachment
(
    id            integer generated by default as identity not null,
    create_by     integer,
    update_by     integer,
    deleted       boolean                                  not null,
    create_at     timestamp without time zone,
    update_at     timestamp without time zone,
    name          varchar(255),
    path          varchar(255),
    content_type  varchar(255),
    original_name varchar(255),
    size          bigint,
    constraint pk_attachment primary key (id)
);

create table role
(
    id          integer generated by default as identity not null,
    create_by   integer,
    update_by   integer,
    deleted     boolean                                  not null,
    create_at   timestamp without time zone,
    update_at   timestamp without time zone,
    name        varchar(255),
    type        smallint,
    permissions varchar[],
    constraint pk_role primary key (id)
);

create table user_profile
(
    id        integer generated by default as identity not null,
    create_by integer,
    update_by integer,
    deleted   boolean                                  not null,
    create_at timestamp without time zone,
    update_at timestamp without time zone,
    user_id   integer,
    banner_id integer,
    constraint pk_userprofile primary key (id)
);

create table user_profile_image_profile
(
    user_profile_id  integer not null,
    image_profile_id integer not null
);

create table users
(
    id         integer generated by default as identity not null,
    create_by  integer,
    update_by  integer,
    deleted    boolean                                  not null,
    create_at  timestamp without time zone,
    update_at  timestamp without time zone,
    first_name varchar(255),
    last_name  varchar(255),
    username   varchar(255),
    password   varchar(255),
    email      varchar(255),
    enable     boolean                                  not null,
    role_id    integer,
    constraint pk_users primary key (id)
);

alter table user_profile
    add constraint fk_userprofile_on_banner foreign key (banner_id) references attachment (id);

alter table user_profile
    add constraint fk_userprofile_on_user foreign key (user_id) references users (id);

alter table users
    add constraint fk_users_on_role foreign key (role_id) references role (id);

alter table user_profile_image_profile
    add constraint fk_useproimapro_on_attachment foreign key (image_profile_id) references attachment (id);

alter table user_profile_image_profile
    add constraint fk_useproimapro_on_user_profile foreign key (user_profile_id) references user_profile (id);